version: '3'

services:
 frontend-app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/frontend/node_modules
      - .:/home/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

