version: '3'

services:
  frontend-app:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/frontend/node_modules
      - .:/home/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
      
  frontend-tests:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - /home/frontend/node_modules
      - .:/home/frontend
    command: ["npm", "run", "test"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  

